command: ["python", "app.py"]
env:
  - name: PORT
    value: "8000"
  - name: N8N_BASIC_AUTH_ACTIVE
    value: "true"
  - name: N8N_BASIC_AUTH_USER
    value: "admin"
  - name: N8N_BASIC_AUTH_PASSWORD
    value: "210794301105nH"